[package]
name = "rustycheckers"
version = "0.1.0"
authors = ["omar-3 <s-omarkhaled@zewailcity.edu.eg>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
